version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm test
  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9f:09:89:34:dd:89:53:33:57:3d:90:55:80:a8:36:e3"
      - run: ssh-keyscan 104.215.156.233 >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: ssh vuong_truong@104.215.156.233 "cd /app/cloud_computing/webapp_frontend; git fetch; 
          git commit -m 'update code when master change'; git merge; sudo docker restart nodejs;";

workflows:
  demo:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master