version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm test
  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0d:e7:65:fb:eb:db:14:66:c0:eb:21:22:39:31:d3:38"
      - run: ssh-keyscan 52.139.201.17 >> ~/.ssh/known_hosts
      
      - run:
          name: Deploy over SSH
          command: ssh happycafe@52.139.201.17 "cd /home/happycafe/source/happycafe/webapp_frontend; git pull; docker restart nodejs;";

workflows:
  demo:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master